const $=x=>document.querySelector(x),$$=x=>[...document.querySelectorAll(x)];
const S={clean:{name:'Clean source',ph:7.2,tds:320,turb:2.1,temp:27.1,metal:8},mining:{name:'Mining-affected',ph:5.8,tds:1180,turb:76,temp:28.6,metal:71},failure:{name:'Verification failure',ph:5.8,tds:1180,turb:76,temp:28.6,metal:88},storm:{name:'Storm runoff',ph:6.4,tds:680,turb:145,temp:25.2,metal:34}};
let sc='clean',busy=false,vol=0,load=0,logs=[],hist=[];
function sensors(d){let a=[['pH','ph','pH',14],['TDS','tds','ppm',2000],['Turbidity','turb','NTU',150],['Temperature','temp','°C',50],['Priority metal','metal','signal %',100]];$('#sensors').innerHTML=a.map(x=>{let v=d[x[1]],bad=(x[1]=='ph'&&(v<6.5||v>8.5))||(x[1]=='tds'&&v>1000)||(x[1]=='turb'&&v>5)||(x[1]=='metal'&&v>60);return `<article class="card sensor ${bad?'bad':''}"><small>${x[0]}</small><div class="value">${v}</div><span>${x[2]}</span><div class="meter"><i style="width:${Math.min(100,v/x[3]*100)}%"></i></div></article>`}).join('')}
function act(o){$('#acts').innerHTML=Object.entries(o).map(([k,v])=>`<div class="act">${k}<b class="${v?'on':'off'}">${v?'● ON':'○ OFF'}</b></div>`).join('')}
function lg(m,t='SYSTEM',bad=false){logs.unshift({m,t,bad,time:new Date().toLocaleTimeString()});$('#log').innerHTML=logs.slice(0,60).map(e=>`<div class="event ${e.bad?'danger':''}"><b>${e.time} ${e.t}</b>${e.m}</div>`).join('')}
function phys(d){let Q=+$('#slider').value,tau=108/Q,clarity=Math.exp(-.009*d.turb),I=34*clarity,dose=I*tau,tds=d.tds*(.18+.02*Math.min(1,Q/4.5)),metal=d.metal*(.12+.06*Math.min(1,Q/4.5)),turb=Math.max(.35,d.turb*Math.exp(-1.9)),dp=.35+.12*Q*Q+load*.018,power=18+7*Q+34*.22;return{Q,tau,I,dose,tds,metal,turb,dp,power}}
function badge(t,c){$('#badge').textContent=t;$('#badge').className=c||'';$('#tankbadge').textContent=t=='SAFE'?'RELEASED':'LOCKED';$('#tankbadge').className=c||''}
async function wait(n){return new Promise(r=>setTimeout(r,n))}
async function run(){if(busy)return;busy=true;$('#run').disabled=true;let d=S[sc],p=phys(d);sensors(d);badge('RUNNING','run');$('#decision').textContent='Characterizing source water…';$('#phase').textContent='Sense';$('#prog').value=8;act({'Pump P1':false,'Valve V1':false,'UV reactor':false,'Output gate':false,'GSM alert':false,'ESP32':true});lg(`Cycle started — ${d.name}`,'CYCLE');await wait(900);lg(`Sensor snapshot: pH ${d.ph}, TDS ${d.tds} ppm, turbidity ${d.turb} NTU`,'SENSE');$('#phase').textContent='Purify';$('#prog').value=38;$('#decision').textContent='Adaptive treatment engaged…';act({'Pump P1':true,'Valve V1':true,'UV reactor':false,'Output gate':false,'GSM alert':false,'ESP32':true});await wait(1300);load=Math.min(100,load+d.turb/30);vol+=p.Q*1.3/60;$('#fill').style.height=Math.min(92,vol/10*92)+'%';$('#vol').textContent=vol.toFixed(2)+' L';lg(`Kinetic model: turbidity ${d.turb.toFixed(1)} → ${p.turb.toFixed(2)} NTU; TDS → ${p.tds.toFixed(0)} ppm`,'PURIFY');$('#phase').textContent='Verify';$('#prog').value=72;$('#decision').textContent='Post-treatment verification…';act({'Pump P1':true,'Valve V1':true,'UV reactor':true,'Output gate':false,'GSM alert':false,'ESP32':true});await wait(1100);let safe=d.ph>=6.5&&d.ph<=8.5&&p.tds<500&&p.turb<1&&p.metal<18&&p.dose>=1200;if(sc==='failure')safe=false;let conf=Math.max(0,Math.min(99,100-Math.abs(p.tds-300)/15-Math.max(0,p.turb-1)*4-Math.max(0,p.metal-18)));$('#conf').textContent=conf.toFixed(0)+'%';$('#rt').textContent=p.tau.toFixed(1)+' s';$('#uv').textContent=p.dose.toFixed(0)+' mJ/cm²';$('#dp').textContent=p.dp.toFixed(2)+' bar';$('#pw').textContent=p.power.toFixed(1)+' W';$('#flow').textContent=p.Q.toFixed(2)+' L/min';$('#energy').textContent=(p.power*1.3/60).toFixed(2)+' Wh';hist.push([d.turb,p.turb]);if(hist.length>14)hist.shift();draw();lg(`UV dose ${p.dose.toFixed(0)} mJ/cm² — verification ${safe?'PASSED':'FAILED'}`,safe?'VERIFY':'ALERT',!safe);$('#phase').textContent='Release';$('#prog').value=100;await wait(500);if(safe){badge('SAFE','safe');$('#decision').textContent='Water passed the simulated release gate.';act({'Pump P1':false,'Valve V1':true,'UV reactor':true,'Output gate':true,'GSM alert':false,'ESP32':true});lg('Release gate OPEN — output authorized.','RELEASE')}else{badge('LOCKOUT','bad');$('#decision').textContent='Verification failed — output remains isolated.';act({'Pump P1':false,'Valve V1':false,'UV reactor':false,'Output gate':false,'GSM alert':true,'ESP32':true});lg('FAIL-SAFE LOCKOUT — output isolated; GSM alert queued.','LOCKOUT',true)}busy=false;$('#run').disabled=false}
function draw(){let c=$('#chart'),x=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=260*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio);w=c.clientWidth;h=260;x.clearRect(0,0,w,h);x.strokeStyle='#223b45';for(let y=25;y<h-30;y+=45){x.beginPath();x.moveTo(35,y);x.lineTo(w-10,y);x.stroke()}if(!hist.length){x.fillStyle='#607984';x.font='12px system-ui';x.fillText('Run a cycle to populate the chart.',35,120);return}x.strokeStyle='#48c8b6';x.lineWidth=2;x.beginPath();hist.forEach((v,i)=>{let px=35+i*(w-50)/Math.max(1,hist.length-1),py=h-30-v[0]/150*(h-60);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.strokeStyle='#9bb6be';x.beginPath();hist.forEach((v,i)=>{let px=35+i*(w-50)/Math.max(1,hist.length-1),py=h-30-v[1]/80*(h-60);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle='#708994';x.fillText('Raw turbidity',35,15);x.fillText('Post-treatment',120,15)}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.p).classList.add('active');if(b.dataset.p==='analytics')draw()});
$$('.scenario').forEach(b=>b.onclick=()=>{$$('.scenario').forEach(x=>x.classList.remove('active'));b.classList.add('active');sc=b.dataset.s;$('#scenarioLabel').textContent=S[sc].name;sensors(S[sc]);badge('READY');$('#decision').textContent='Ready for source-water characterization'});
$('#slider').oninput=e=>$('#flowv').textContent=(+e.target.value).toFixed(2)+' L/min';$('#run').onclick=run;sensors(S.clean);act({'Pump P1':false,'Valve V1':false,'UV reactor':false,'Output gate':false,'GSM alert':false,'ESP32':true});$('#log').innerHTML='<span style="color:#607984">No events yet.</span>';draw()
