const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DATA={
clean:{name:'Clean source',ph:7.2,tds:320,turb:2.1,temp:27.1,metal:8},
mining:{name:'Mining affected',ph:5.8,tds:1180,turb:76,temp:28.6,metal:52},
storm:{name:'Storm runoff',ph:6.4,tds:680,turb:145,temp:25.2,metal:20},
metal:{name:'Priority-metal alert',ph:6.7,tds:740,turb:9,temp:27.8,metal:91}
};
let selected='clean',busy=false,litres=0,logs=[],load=0;
function render(d){let a=[['pH','ph','pH',v=>v>=6.5&&v<=8.5],['TDS','tds','ppm',v=>v<500],['Turbidity','turb','NTU',v=>v<5],['Temperature','temp','°C',v=>v>=5&&v<=35],['Priority metal','metal','signal %',v=>v<18]];$('#tests').innerHTML=a.map(x=>{let ok=x[3](d[x[1]]),warn=!ok&&((x[1]=='tds'&&d[x[1]]<1400)||(x[1]=='metal'&&d[x[1]]<80));return `<div class="test ${ok?'ok':warn?'warn':'bad'}"><small>${x[0]}</small><b>${d[x[1]]} ${x[2]}</b></div>`}).join('');$('#sourceName').textContent=d.name;let bad=d.ph<6.5||d.ph>8.5||d.tds>=1000||d.turb>=5||d.metal>=60;$('#quality').textContent=bad?'ATTENTION':'GOOD';}
function alertMsg(text,bad=false){$('#alerts').innerHTML=`<div class="alert ${bad?'danger':''}"><b>${bad?'⚠ ALERT':'● INFO'}</b>${text}</div>`}
function log(msg,bad=false){logs.unshift({t:new Date().toLocaleTimeString(),m:msg,b:bad});$('#historyList').innerHTML=logs.map(x=>`<div class="history-row"><small>${x.t}</small><b class="${x.b?'bad':''}">${x.b?'ALERT':'TEST'}</b><span>${x.m}</span><small>${x.b?'LOCKOUT':'SIMULATED'}</small></div>`).join('')||'<span style="color:#617d8b">No tests completed.</span>'}
function stage(name,i){$$('.stage').forEach((x,n)=>{x.classList.toggle('active',n===i);x.classList.toggle('done',n<i)});$('#phase').textContent=name;$('#progress').style.width=(i/7*100)+'%'}
function wait(n){return new Promise(r=>setTimeout(r,n))}
function model(d){let Q=+$('#flow').value,tau=90/Q,uvI=30*Math.exp(-.009*d.turb),dose=uvI*tau;let turb=d.turb*Math.exp(-2.25),tds=d.tds*.25,metal=d.metal*.10;if(d.turb>80)turb*=.65;return{Q,tau,dose,turb,tds,metal,power:18+7*Q+6,energy:(18+7*Q+6)*1.2/60}}
async function run(){if(busy)return;busy=true;$('#run').disabled=true;let d=DATA[selected],p=model(d);render(d);$('#statusTitle').textContent='TEST IN PROGRESS';$('#statusSub').textContent='Water is moving through the simulated treatment train.';$('#statusBadge').textContent='RUNNING';$('#statusBadge').className='run';$('#action').textContent='Adaptive treatment selected';$('#gate').textContent='LOCKED';$('#gate').className='';alertMsg('Test started. Output remains isolated until final verification passes.');log(`Started ${d.name} at ${p.Q.toFixed(2)} L/min`);for(let i=0;i<8;i++){let names=['Intake','Screening','Coagulation + flocculation','Media filtration','Carbon / polish','UV disinfection','Final verification','Release decision'];stage(names[i],i);$('#progress').style.width=(i/7*100)+'%';await wait(i===0?500:650);if(i===2)$('#action').textContent='Reducing suspended particle load';if(i===3)$('#action').textContent='Depth filtration active';if(i===4)$('#action').textContent='Adsorption / fine polishing';if(i===5)$('#action').textContent='Applying UV exposure';if(i===6)$('#action').textContent='Re-testing treated water…'}let safe=d.ph>=6.5&&d.ph<=8.5&&p.tds<500&&p.turb<1&&p.metal<18&&p.dose>=900;if(selected==='metal')safe=false;$('#progress').style.width='100%';if(safe){$('#statusTitle').textContent='WATER RELEASE AUTHORIZED';$('#statusSub').textContent='Final simulated verification passed all release checks.';$('#statusBadge').textContent='SAFE';$('#statusBadge').className='good';$('#gate').textContent='OPEN';$('#gate').className='open';$('#tankState').textContent='RELEASED';$('#action').textContent='Release treated water';alertMsg(`Verification passed: turbidity ${p.turb.toFixed(2)} NTU, TDS ${p.tds.toFixed(0)} ppm, metal signal ${p.metal.toFixed(1)}%. Output gate opened.`);log(`PASS — treated water released. Turbidity ${p.turb.toFixed(2)} NTU; TDS ${p.tds.toFixed(0)} ppm.`)}else{$('#statusTitle').textContent='CONTAMINATION / QUALITY ALERT';$('#statusSub').textContent='Final verification failed. The output gate remains isolated.';$('#statusBadge').textContent='LOCKOUT';$('#statusBadge').className='bad';$('#gate').textContent='LOCKED';$('#action').textContent='Isolate + alert operator';let why=p.metal>=18?'priority-metal signal remains high':p.turb>=1?'turbidity remains high':p.tds>=500?'TDS remains high':p.dose<900?'insufficient UV exposure':'pH outside release window';alertMsg(`FAIL-SAFE ALERT: ${why}. Output isolated and operator alert generated.`,true);log(`FAIL — ${why}; automatic lockout activated.`,true)}litres+=p.Q*1.2/60;$('#tankFill').style.height=Math.min(90,litres*9)+'%';$('#litres').textContent=litres.toFixed(2)+' L';$('#liveFlow').textContent=p.Q.toFixed(2)+' L/min';$('#energy').textContent=p.energy.toFixed(2)+' Wh';busy=false;$('#run').disabled=false}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.page).classList.add('active')});
$$('.scenario').forEach(b=>b.onclick=()=>{$$('.scenario').forEach(x=>x.classList.remove('active'));b.classList.add('active');selected=b.dataset.s;render(DATA[selected]);$('#statusTitle').textContent='READY FOR WATER TEST';$('#statusSub').textContent='Select a source condition and start the simulated treatment cycle.';$('#statusBadge').textContent='READY';$('#statusBadge').className='';$('#gate').textContent='LOCKED';$('#gate').className='';$('#tankState').textContent='ISOLATED';$('#action').textContent='Waiting for test';alertMsg('Scenario selected. Start the test to run the complete purification and verification cycle.')});
$('#flow').oninput=e=>$('#flowValue').textContent=(+e.target.value).toFixed(2)+' L/min';$('#run').onclick=run;setInterval(()=>$('#time').textContent=new Date().toLocaleTimeString(),1000);render(DATA.clean);log();
